### ISSUE TITLE
make not properly linking libraries (sys/shm.h)

### ISSUE THREAD

**Issue by dviole** [numactl/numactl#240]
### The Issue

I am trying to cross-compile numactl for an android device. To do so, I am working in Ubuntu 24.04.1 LTS (WSL on Windows 11 x86-64 device).
While running make, the following issues come up:

> /usr/local/sbin/numactl# make
> make  all-am
> make[1]: Entering directory '/usr/local/sbin/numactl'
>   CC       numactl-numactl.o
>   CC       numactl-util.o
>   CC       numactl-shm.o
> shm.c:106:10: error: call to undeclared function 'shmget'; ISO C99 and later do not support implicit function declarations [-Wimplicit-
> function-declaration]
>   106 |         shmfd = shmget(key, shmlen, shmflags);
>       |                 ^
> shm.c:120:7: error: call to undeclared function 'shmctl'; ISO C99 and later do not support implicit function declarations [-Wimplicit-
> function-declaration]
>   120 |                 if (shmctl(shmfd, IPC_STAT, &s) < 0)
>       |                     ^
> shm.c:125:11: error: call to undeclared function 'shmat'; ISO C99 and later do not support implicit function declarations [-Wimplicit-
> function-declaration]
>   125 |         shmptr = shmat(shmfd, NULL, 0);
>       |                  ^
> shm.c:125:9: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
>   125 |         shmptr = shmat(shmfd, NULL, 0);
>       |                ^ ~~~~~~~~~~~~~~~~~~~~~
> 4 errors generated.
> make[1]: *** [Makefile:1115: numactl-shm.o] Error 1
> make[1]: Leaving directory '/usr/local/sbin/numactl'
> make: *** [Makefile:752: all] Error 2

I tried editing some of the declarations (changing them to void *) and adding flags to the make command `make LDFLAGS="-lc -lrt -(f)permissive"` but it did not resolve the issue either.

### Getting to the issue

> git clone https://github.com/numactl/numactl.git 
> cd numactl
> ./autogen.sh
> ./configure --host=aarch64-linux-android --prefix=/usr/local/sbin/numactl/
> make

**Comment by andikleen** [comment]
The file includes <sys/shm.h> which is the canonical place for shmget/shmat.

Can you grep -r the Android include files and see where those are declared, or if it needs some special defines?

**Comment by luochenglcs** [comment]
https://github.com/aosp-mirror/platform_bionic/blob/main/libc/include/sys/shm.h#L52

**Comment by luochenglcs** [comment]
shmget/shmat function declaration：
https://github.com/aosp-mirror/platform_bionic/blob/main/libc/include/sys/shm.h#L52
https://github.com/aosp-mirror/platform_bionic/blob/main/libc/include/android/versioning.h#L29

based on source code, it appears that support weak references or minSdkVersion >=26 is necessary to effectively utilize the shmget/shmctl API. For further guidance, refer to the Android development manual at https://developer.android.com/ndk/guides/using-newer-apis. To potentially resolve issues, you might consider executing the command `make -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -Werror=unguarded-availability`.
