### ISSUE TITLE
Latest release doesn't build with MUSL C run-time

### ISSUE THREAD

**Issue by pprindeville** [numactl/numactl#185]
However, the changes in 851bbd5 look like they'd fix that.

When is the next release due out?

**Comment by pprindeville** [comment]
cc: @zokl

**Comment by douglas-raillard-arm** [comment]
I think I hit the same issues:
```
make[1]: Entering directory '/tmp/tmpee6k_7gv/x86_64/source/numactl'
  CC       numactl.o
  CC       util.o
  CC       shm.o
In file included from shm.c:27:
/usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
      |  ^~~~~~~
shm.c: In function 'attach_shared':
shm.c:138:23: error: storage size of 'st' isn't known
  138 |         struct stat64 st;
      |                       ^~
shm.c:149:13: warning: implicit declaration of function 'fstat64'; did you mean 'fstatat'? [-Wimplicit-function-declaration]
  149 |         if (fstat64(shmfd, &st) < 0)
      |             ^~~~~~~
      |             fstatat
shm.c:156:21: warning: implicit declaration of function 'ftruncate64'; did you mean 'ftruncate'? [-Wimplicit-function-declaration]
  156 |                 if (ftruncate64(shmfd, shmlen + shmoffset) < 0) {
      |                     ^~~~~~~~~~~
      |                     ftruncate
shm.c:171:18: warning: implicit declaration of function 'mmap64'; did you mean 'mmap'? [-Wimplicit-function-declaration]
  171 |         shmptr = mmap64(NULL, shmlen, PROT_READ | PROT_WRITE, MAP_SHARED, shmfd, shmoffset);
      |                  ^~~~~~
      |                  mmap
shm.c:171:16: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  171 |         shmptr = mmap64(NULL, shmlen, PROT_READ | PROT_WRITE, MAP_SHARED, shmfd, shmoffset);
      |                ^
shm.c:138:23: warning: unused variable 'st' [-Wunused-variable]
  138 |         struct stat64 st;
      |                       ^~
make[1]: *** [Makefile:1064: shm.o] Error 1
make[1]: Leaving directory '/tmp/tmpee6k_7gv/x86_64/source/numactl'
make: *** [Makefile:754: all] Error 2
```

The build fails on Alpine Linux 3.19 (musl libc) but works on 3.18. 

On 3.18, there still are these warnings:
```
/usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
```

**Comment by luochenglcs** [comment]
Yes, it's the same problem。

**Comment by andikleen** [comment]
Yes we should do a release soon.

**Comment by luochenglcs** [comment]
@pprindeville @douglas-raillard-arm The new version has been released, you can try again.

**Comment by zokl** [comment]
> @pprindeville @douglas-raillard-arm The new version has been released, you can try again.

Hi, thank you. I will test it.
